# Generated by Django 6.1 on 2026-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='test',
            name='syllabus',
            field=models.ManyToManyField(help_text='Select the topics covered in this test', to='quiz.topic'),
        ),
    ]
