# Generated by Django 6.1 on 2026-08-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='syllabus',
        ),
        migrations.CreateModel(
            name='TestTopicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=5, help_text='Number of questions to randomly pick')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='quiz.test')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic')),
            ],
        ),
    ]
